#!/usr/bin/env -S deno run -Aq

import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export interface WorkspaceManifest {
  version: string;
  author: {
    name: string;
    email?: string;
    url?: string;
  };
}

export interface PackageTextOwnership {
  mode?: "generated" | "preserve" | "custom";
  template?: string;
  footerLinks?: Record<string, string>;
  notes?: string[];
  acknowledgements?: string[];
  copyright?: string[];
}

export interface PackageMetadata {
  name?: string;
  description: string;
  keywords: string[];
  exports?: Record<string, string | ExportConditionMap>;
  dependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  publishConfig?: Record<string, unknown>;
  readme?: PackageTextOwnership;
  license?: PackageTextOwnership;
  manifest?: Record<string, unknown>;
}

export interface TemplatesMetadata {
  packages: Record<string, PackageMetadata>;
}

export interface ExportConditionMap {
  types?: string;
  source?: string;
  deno?: string;
  default?: string;
  require?: {
    types?: string;
    default?: string;
  };
}

export interface PackageJson {
  name: string;
  version?: string;
  description?: string;
  author?: WorkspaceManifest["author"];
  license?: string;
  type?: string;
  homepage?: string;
  repository?: Record<string, unknown>;
  bugs?: Record<string, unknown>;
  keywords?: string[];
  main?: string;
  module?: string;
  types?: string;
  files?: string[];
  exports?: Record<string, string | ExportConditionMap>;
  dependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  publishConfig?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface CliOptions {
  apply?: boolean;
  json?: boolean;
}

export interface ManagedFilePlan {
  packageId: string;
  path: string;
  kind: "package.json" | "README.md" | "LICENSE";
  mode: "generated" | "preserved" | "ambiguous";
  reason: string;
  action: "unchanged" | "create" | "update" | "skip";
  before?: string;
  after?: string;
}

export interface SyncReport {
  apply: boolean;
  backupDir: string | null;
  plans: ManagedFilePlan[];
}

const ROOT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PACKAGES_DIR = join(ROOT_DIR, "packages");
const TEMPLATES_DIR = join(ROOT_DIR, "templates");
const TEMPLATE_ROOT = join(TEMPLATES_DIR, "packages", "{{pkg.id}}");
const SOURCE_FILE_CACHE = new Map<string, string[]>();

const GENERATED_README_MARKER = "<!-- @generated by sync_packages -->";
const LEGACY_README_TEMPLATE = `# \`{{pkg.name}}\`

{{pkg.description}}

## Package

- Package: \`{{pkg.name}}\`
- Directory: \`{{pkg.directory}}\`
- Homepage: {{pkg.homepage}}
- Source: {{pkg.sourceUrl}}
- Issues: {{pkg.bugs.url}}
- License: MIT

## Development

This file is generated from the monorepo templates in \`templates/\` via
\`deno task sync:packages\`.`;

const README_TEMPLATE = resolve(
  TEMPLATE_ROOT,
  "README.template.md",
);
const LICENSE_TEMPLATE = resolve(
  TEMPLATE_ROOT,
  "LICENSE.template",
);

const GENERATED_MANIFEST_KEYS = new Set([
  "name",
  "version",
  "description",
  "author",
  "license",
  "type",
  "homepage",
  "repository",
  "bugs",
  "keywords",
  "main",
  "module",
  "types",
  "files",
  "exports",
  "dependencies",
  "peerDependencies",
  "devDependencies",
  "publishConfig",
]);

function normalizeNewlines(text: string): string {
  return text.replace(/\r\n/g, "\n");
}

function normalizeForCompare(text: string): string {
  return normalizeNewlines(text)
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function toRelativePath(from: string, to: string): string {
  return relative(from, to).replaceAll("\\", "/");
}

function packageSort(left: string, right: string): number {
  if (left === "." && right !== ".") return -1;
  if (right === "." && left !== ".") return 1;
  return left.localeCompare(right);
}

function parseArgs(args: string[]): CliOptions {
  return {
    apply: args.includes("--apply"),
    json: args.includes("--json"),
  };
}

function stringifyJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function renderTemplate(
  template: string,
  context: Record<string, unknown>,
): string {
  return template.replace(
    /{{\s*(json\s+)?([^}]+?)\s*}}/g,
    (_match, jsonHelper, rawPath) => {
      const value = resolveValue(context, rawPath.trim());
      if (jsonHelper) {
        return JSON.stringify(value, null, 2);
      }
      return String(value ?? "");
    },
  );
}

function resolveValue(context: Record<string, unknown>, path: string): unknown {
  const parts = path.split(".");
  let current: unknown = context;
  for (const part of parts) {
    if (!part) continue;
    if (current === null || typeof current !== "object" || !(part in current)) {
      throw new Error(`Unknown template value: ${path}`);
    }
    current = (current as Record<string, unknown>)[part];
  }
  return current;
}

function isInternalExportPath(path: string): boolean {
  return path.split("/").some((part) =>
    part.startsWith("_") || part.endsWith(".test.ts") || part.endsWith(".test.js")
  );
}

function toKebabSegment(segment: string): string {
  return segment
    .replaceAll("_", "-")
    .replaceAll(".", "-")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-")
    .toLowerCase();
}

function normalizeExportKey(key: string): string {
  if (key === ".") return ".";
  const normalized = key
    .replace(/^\.\//, "")
    .split(/[\\/]/)
    .filter(Boolean)
    .map(toKebabSegment)
    .join("/");
  return `./${normalized}`;
}

function normalizeSourceTarget(path: string): string {
  const normalized = path.replace(/^\.\//, "");
  if (normalized.startsWith("src/")) return `./${normalized}`;
  if (normalized.startsWith("index.")) return `./${normalized}`;
  if (normalized.includes("/") || /\.[cm]?[jt]sx?$/.test(normalized)) {
    return `./${normalized}`;
  }
  return `./src/${normalized}`;
}

function toBuiltPath(sourcePath: string, format: "esm" | "cjs", ext: "js" | "d.ts"): string {
  const normalized = sourcePath.replace(/^\.\//, "");
  const withoutPrefix = normalized.startsWith("src/")
    ? normalized.slice("src/".length)
    : normalized.replace(/^index\.[^/]+$/, "index.ts");
  const withoutExt = withoutPrefix.replace(/\.[cm]?[jt]sx?$/, "");
  return `./${format}/${withoutExt}.${ext}`;
}

function toConditionalExport(sourcePath: string): ExportConditionMap {
  const normalized = normalizeSourceTarget(sourcePath);
  return {
    types: toBuiltPath(normalized, "esm", "d.ts"),
    source: normalized,
    deno: normalized,
    require: {
      types: toBuiltPath(normalized, "cjs", "d.ts"),
      default: toBuiltPath(normalized, "cjs", "js"),
    },
    default: toBuiltPath(normalized, "esm", "js"),
  };
}

function listPackageSourceFiles(packageDir: string): string[] {
  const cached = SOURCE_FILE_CACHE.get(packageDir);
  if (cached) return cached;

  const files: string[] = [];
  const srcDir = join(packageDir, "src");
  try {
    const stat = Deno.statSync(srcDir);
    if (stat.isDirectory) {
      const walk = (dir: string) => {
        for (const entry of Deno.readDirSync(dir)) {
          const fullPath = join(dir, entry.name);
          if (entry.isDirectory) {
            walk(fullPath);
            continue;
          }
          if (!entry.isFile || isInternalExportPath(toRelativePath(packageDir, fullPath))) {
            continue;
          }
          files.push(`./${toRelativePath(packageDir, fullPath)}`);
        }
      };
      walk(srcDir);
    }
  } catch {
    // package may not expose a src directory
  }

  SOURCE_FILE_CACHE.set(packageDir, files);
  return files;
}

function resolveExistingSourceTarget(packageDir: string, sourcePath: string): string {
  const normalized = normalizeSourceTarget(sourcePath);
  const fullPath = join(packageDir, normalized.replace(/^\.\//, ""));
  try {
    if (Deno.statSync(fullPath).isFile) {
      return normalized;
    }
  } catch {
    // fall through to basename lookup
  }

  const basename = normalized.split("/").at(-1);
  if (!basename) return normalized;

  const matches = listPackageSourceFiles(packageDir).filter((candidate) =>
    candidate.endsWith(`/${basename}`) || candidate === `./${basename}`
  );
  return matches.length === 1 ? matches[0] : normalized;
}

function cleanExports(
  packageDir: string,
  exportsMap: Record<string, string | ExportConditionMap> | undefined,
  defaultEntry = "./src/index.ts",
): Record<string, ExportConditionMap> {
  const cleaned = new Map<string, ExportConditionMap>();
  const source = exportsMap ?? { ".": defaultEntry };
  for (const [rawKey, rawValue] of Object.entries(source)) {
    const key = normalizeExportKey(rawKey);
    if (key === "./index" || key.endsWith("/index")) continue;
    if (
      key !== "." && key.slice(2).split("/").some((segment) => segment.startsWith("_"))
    ) {
      continue;
    }

    const sourcePath = typeof rawValue === "string"
      ? resolveExistingSourceTarget(packageDir, rawValue)
      : rawValue.source ?? rawValue.deno ??
        rawValue.default?.replace(/^\.\/(?:esm|cjs)\//, "./src/")
          .replace(/\.js$/, ".ts") ??
        rawValue.types?.replace(/^\.\/esm\//, "./src/").replace(/\.d\.ts$/, ".ts");
    const resolvedSourcePath = sourcePath
      ? resolveExistingSourceTarget(packageDir, sourcePath)
      : sourcePath;
    if (!resolvedSourcePath || isInternalExportPath(resolvedSourcePath.replace(/^\.\//, ""))) {
      continue;
    }
    cleaned.set(key, toConditionalExport(resolvedSourcePath));
  }

  if (!cleaned.has(".")) {
    cleaned.set(".", toConditionalExport(resolveExistingSourceTarget(packageDir, defaultEntry)));
  }

  return Object.fromEntries(
    [...cleaned.entries()].sort(([left], [right]) => packageSort(left, right)),
  );
}

function normalizeDeps(
  deps: Record<string, string> | undefined,
  version: string,
  workspacePackageNames: ReadonlySet<string>,
): Record<string, string> | undefined {
  if (!deps || Object.keys(deps).length === 0) return undefined;
  const out: Record<string, string> = {};
  for (const name of Object.keys(deps).sort((left, right) => left.localeCompare(right))) {
    out[name] = workspacePackageNames.has(name) ? `workspace:${version}` : deps[name];
  }
  return out;
}

function makeHomePage(id: string): string {
  return `https://github.com/nberlette/dawm/tree/main/packages/${id}#readme`;
}

function makeBugsUrl(name: string): string {
  return `https://github.com/nberlette/dawm/issues/new?title=${
    encodeURIComponent(`[${name}] `)
  }`;
}

function isReadmeLegacyGenerated(readme: string, context: Record<string, unknown>): boolean {
  if (readme.includes(GENERATED_README_MARKER)) return true;
  const legacy = renderTemplate(LEGACY_README_TEMPLATE, context);
  if (normalizeForCompare(readme) === normalizeForCompare(legacy)) return true;
  const pkg = context.pkg as Record<string, unknown>;
  const checks = [
    `# \`${pkg.name}\``,
    "## Package",
    `- Package: \`${pkg.name}\``,
    `- Directory: \`${pkg.directory}\``,
    `- Homepage: ${pkg.homepage}`,
    `- Source: ${pkg.sourceUrl}`,
    `- Issues: ${(pkg.bugs as Record<string, unknown>).url}`,
    "- License: MIT",
    "## Development",
    "`deno task sync:packages`",
  ];
  return checks.every((check) => normalizeForCompare(readme).includes(normalizeForCompare(check)));
}

function makeDefaultFooterLinks(name: string): Record<string, string> {
  return {
    github: "https://github.com/nberlette/dawm/#readme",
    issues: "https://github.com/nberlette/dawm/issues",
    docs: `https://jsr.io/${name}`,
    npm: `https://www.npmjs.com/package/${name}`,
  };
}

function buildReadmeContext(
  id: string,
  metadata: PackageMetadata,
  manifest: PackageJson,
): Record<string, unknown> {
  const footerLinks = {
    ...makeDefaultFooterLinks(manifest.name),
    ...(metadata.readme?.footerLinks ?? {}),
  };

  const exportsList = Object.keys(manifest.exports ?? {})
    .map((key) => `- \`${key}\``)
    .join("\n") || "- `.`";
  const notes = metadata.readme?.notes?.length
    ? metadata.readme.notes.map((note) => `- ${note}`).join("\n")
    : "- No package-specific notes yet.";
  const acknowledgements = metadata.readme?.acknowledgements?.length
    ? metadata.readme.acknowledgements.map((item) => `- ${item}`).join("\n")
    : "- This package is part of the dawm monorepo.";
  return {
    generated_marker: GENERATED_README_MARKER,
    pkg: {
      id,
      name: manifest.name,
      description: metadata.description,
      directory: `packages/${id}`,
      homepage: makeHomePage(id),
      sourceUrl: `https://github.com/nberlette/dawm/tree/main/packages/${id}/src`,
      bugs: { url: makeBugsUrl(manifest.name) },
      exports: exportsList,
      notes,
      acknowledgements,
      footerLinks,
    },
  };
}

function buildLicenseContext(
  metadata: PackageMetadata,
  workspace: WorkspaceManifest,
  workspaceLicenseText: string,
): Record<string, unknown> {
  const copyright = metadata.license?.copyright?.length
    ? metadata.license.copyright.join("\n\n")
    : workspaceLicenseText.trimEnd();
  return {
    workspace: {
      author: workspace.author,
    },
    pkg: {
      copyright,
    },
  };
}

function buildPackageManifest(
  id: string,
  packageDir: string,
  metadata: PackageMetadata,
  currentManifest: PackageJson | null,
  workspace: WorkspaceManifest,
  workspacePackageNames: ReadonlySet<string>,
): PackageJson {
  const defaultName = id === "dawm" ? "dawm" : `dawm-${id}`;
  const name = metadata.name ?? currentManifest?.name ?? defaultName;
  const defaultEntry = "./src/index.ts";
  const exports = cleanExports(
    packageDir,
    metadata.exports ?? currentManifest?.exports,
    defaultEntry,
  );
  const passthrough = Object.fromEntries(
    Object.entries(currentManifest ?? {}).filter(([key]) => !GENERATED_MANIFEST_KEYS.has(key)),
  );
  const publishConfig = metadata.publishConfig ?? currentManifest?.publishConfig;
  const merged: PackageJson = {
    ...passthrough,
    ...(metadata.manifest ?? {}),
    name,
    version: workspace.version,
    description: metadata.description,
    author: workspace.author,
    license: "MIT",
    type: "module",
    homepage: makeHomePage(id),
    repository: {
      type: "git",
      url: "git+https://github.com/nberlette/dawm.git",
      directory: `packages/${id}`,
    },
    bugs: {
      url: makeBugsUrl(name),
    },
    keywords: Array.from(new Set(["dawm", ...metadata.keywords])).sort((left, right) =>
      left.localeCompare(right)
    ),
    main: "./cjs/index.js",
    module: "./esm/index.js",
    types: "./esm/index.d.ts",
    files: ["src", "esm", "cjs", "README.md", "LICENSE"],
    exports,
    dependencies: normalizeDeps(
      metadata.dependencies ?? currentManifest?.dependencies,
      workspace.version,
      workspacePackageNames,
    ),
    peerDependencies: normalizeDeps(
      metadata.peerDependencies ?? currentManifest?.peerDependencies,
      workspace.version,
      workspacePackageNames,
    ),
    devDependencies: normalizeDeps(
      metadata.devDependencies ?? currentManifest?.devDependencies,
      workspace.version,
      workspacePackageNames,
    ),
    publishConfig,
  };
  return Object.fromEntries(
    Object.entries(merged).filter(([, value]) =>
      value !== undefined && (!Array.isArray(value) || value.length > 0)
    ),
  ) as PackageJson;
}

async function readTextIfExists(path: string): Promise<string | null> {
  try {
    const stat = await Deno.stat(path);
    if (!stat.isFile) return null;
  } catch {
    return null;
  }
  return await Deno.readTextFile(path);
}

async function ensureDir(path: string): Promise<void> {
  await Deno.mkdir(path, { recursive: true });
}

async function copyToBackup(root: string, backupDir: string, path: string): Promise<void> {
  const relativePath = toRelativePath(root, path);
  const destination = join(backupDir, relativePath);
  await ensureDir(dirname(destination));
  await Deno.copyFile(path, destination);
}

async function atomicWrite(path: string, text: string): Promise<void> {
  await ensureDir(dirname(path));
  const tempPath = `${path}.tmp-${crypto.randomUUID()}`;
  await Deno.writeTextFile(tempPath, text);
  await Deno.rename(tempPath, path);
}

function isLicenseGenerated(
  current: string,
  rendered: string,
): boolean {
  return normalizeForCompare(current) === normalizeForCompare(rendered);
}

function makeFilePlan(
  packageId: string,
  path: string,
  kind: ManagedFilePlan["kind"],
  mode: ManagedFilePlan["mode"],
  reason: string,
  before: string | null,
  after: string,
): ManagedFilePlan {
  const action = before === null
    ? mode === "generated" ? "create" : "skip"
    : before === after
    ? "unchanged"
    : mode === "generated"
    ? "update"
    : "skip";
  return {
    packageId,
    path,
    kind,
    mode,
    reason,
    action,
    before: before ?? undefined,
    after,
  };
}

async function collectWorkspacePackageNames(
  packagesDir: string,
  templates: TemplatesMetadata,
): Promise<Set<string>> {
  const names = new Set<string>();
  for (const id of Object.keys(templates.packages).sort()) {
    const manifestPath = join(packagesDir, id, "package.json");
    const manifestText = await readTextIfExists(manifestPath);
    if (manifestText) {
      names.add((JSON.parse(manifestText) as PackageJson).name);
      continue;
    }
    names.add(templates.packages[id].name ?? (id === "dawm" ? "dawm" : `dawm-${id}`));
  }
  return names;
}

async function buildPlansForPackage(
  rootDir: string,
  workspace: WorkspaceManifest,
  workspaceLicenseText: string,
  templates: TemplatesMetadata,
  workspacePackageNames: ReadonlySet<string>,
  packageId: string,
): Promise<ManagedFilePlan[]> {
  const metadata = templates.packages[packageId];
  const packageDir = join(rootDir, "packages", packageId);
  try {
    const stat = await Deno.stat(packageDir);
    if (!stat.isDirectory) return [];
  } catch {
    return [];
  }

  const currentManifestText = await readTextIfExists(join(packageDir, "package.json"));
  const currentManifest = currentManifestText
    ? JSON.parse(currentManifestText) as PackageJson
    : null;

  const manifest = buildPackageManifest(
    packageId,
    packageDir,
    metadata,
    currentManifest,
    workspace,
    workspacePackageNames,
  );
  const manifestText = stringifyJson(manifest);

  const readmeContext = buildReadmeContext(packageId, metadata, manifest);
  const readmeTemplate = await Deno.readTextFile(README_TEMPLATE);
  const renderedReadme = `${renderTemplate(readmeTemplate, readmeContext).trimEnd()}\n`;

  const licenseContext = buildLicenseContext(metadata, workspace, workspaceLicenseText);
  const licenseTemplate = await Deno.readTextFile(LICENSE_TEMPLATE);
  const renderedLicense = `${renderTemplate(licenseTemplate, licenseContext).trimEnd()}\n`;

  const plans: ManagedFilePlan[] = [];
  plans.push(
    makeFilePlan(
      packageId,
      join(packageDir, "package.json"),
      "package.json",
      "generated",
      "package manifests are always generator-managed",
      currentManifestText,
      manifestText,
    ),
  );

  const readmePath = join(packageDir, "README.md");
  const currentReadme = await readTextIfExists(readmePath);
  const readmeMode = metadata.readme?.mode ?? "generated";
  if (readmeMode === "preserve" || readmeMode === "custom") {
    plans.push(
      makeFilePlan(
        packageId,
        readmePath,
        "README.md",
        "preserved",
        `README ownership is '${readmeMode}' in templates metadata`,
        currentReadme,
        currentReadme ?? renderedReadme,
      ),
    );
  } else if (currentReadme === null || isReadmeLegacyGenerated(currentReadme, readmeContext)) {
    plans.push(
      makeFilePlan(
        packageId,
        readmePath,
        "README.md",
        "generated",
        currentReadme === null
          ? "README is missing and will be generated"
          : "README matches generated markers or legacy generated structure",
        currentReadme,
        renderedReadme,
      ),
    );
  } else {
    plans.push(
      makeFilePlan(
        packageId,
        readmePath,
        "README.md",
        "ambiguous",
        "README does not match generated markers or legacy fingerprints; left untouched",
        currentReadme,
        currentReadme,
      ),
    );
  }

  const licensePath = join(packageDir, "LICENSE");
  const currentLicense = await readTextIfExists(licensePath);
  const licenseMode = metadata.license?.mode ?? "generated";
  if (licenseMode === "preserve" || licenseMode === "custom") {
    plans.push(
      makeFilePlan(
        packageId,
        licensePath,
        "LICENSE",
        "preserved",
        `LICENSE ownership is '${licenseMode}' in templates metadata`,
        currentLicense,
        currentLicense ?? renderedLicense,
      ),
    );
  } else if (currentLicense === null || isLicenseGenerated(currentLicense, renderedLicense)) {
    plans.push(
      makeFilePlan(
        packageId,
        licensePath,
        "LICENSE",
        "generated",
        currentLicense === null
          ? "LICENSE is missing and will be generated"
          : "LICENSE matches the generated template content",
        currentLicense,
        renderedLicense,
      ),
    );
  } else {
    plans.push(
      makeFilePlan(
        packageId,
        licensePath,
        "LICENSE",
        "ambiguous",
        "LICENSE differs from generated content and will be preserved",
        currentLicense,
        currentLicense,
      ),
    );
  }

  return plans;
}

export async function runSyncPackages(
  rootDir = ROOT_DIR,
  options: CliOptions = {},
): Promise<SyncReport> {
  const workspacePath = join(rootDir, "deno.json");
  const templatesPath = join(rootDir, "templates", "packages.json");
  const workspace = JSON.parse(
    await Deno.readTextFile(workspacePath),
  ) as WorkspaceManifest;
  const templates = JSON.parse(
    await Deno.readTextFile(templatesPath),
  ) as TemplatesMetadata;
  const workspaceLicenseText = await Deno.readTextFile(join(rootDir, "LICENSE"));
  const workspacePackageNames = await collectWorkspacePackageNames(
    join(rootDir, "packages"),
    templates,
  );

  const plans: ManagedFilePlan[] = [];
  for (const packageId of Object.keys(templates.packages).sort()) {
    plans.push(
      ...(await buildPlansForPackage(
        rootDir,
        workspace,
        workspaceLicenseText,
        templates,
        workspacePackageNames,
        packageId,
      )),
    );
  }

  let backupDir: string | null = null;
  if (options.apply) {
    const timestamp = new Date().toISOString().replaceAll(":", "-");
    backupDir = join("/tmp", "dawm-sync-packages", timestamp);
    await ensureDir(backupDir);
    for (const plan of plans) {
      if (plan.mode !== "generated") continue;
      if (plan.action !== "create" && plan.action !== "update") continue;
      if (plan.before != null) {
        await copyToBackup(rootDir, backupDir, plan.path);
      }
      await atomicWrite(plan.path, plan.after ?? "");
    }
  }

  return {
    apply: !!options.apply,
    backupDir,
    plans,
  };
}

function printHumanReport(report: SyncReport): void {
  const summary = {
    changed: 0,
    preserved: 0,
    ambiguous: 0,
    unchanged: 0,
  };
  for (const plan of report.plans) {
    if (plan.mode === "ambiguous") summary.ambiguous++;
    else if (plan.mode === "preserved") summary.preserved++;
    else if (plan.action === "unchanged") summary.unchanged++;
    else if (plan.action === "create" || plan.action === "update") summary.changed++;
  }

  console.log(
    `${report.apply ? "Applied" : "Planned"} sync for ${report.plans.length} managed files`,
  );
  if (report.backupDir) {
    console.log(`Backup: ${report.backupDir}`);
  }
  console.log(
    `Changed: ${summary.changed} | Preserved: ${summary.preserved} | Ambiguous: ${summary.ambiguous} | Unchanged: ${summary.unchanged}`,
  );
  for (const plan of report.plans) {
    const rel = toRelativePath(ROOT_DIR, plan.path);
    console.log(
      `${plan.action.padEnd(9)} ${plan.mode.padEnd(10)} ${rel} (${plan.reason})`,
    );
  }
}

if (import.meta.main) {
  const options = parseArgs(Deno.args);
  const report = await runSyncPackages(ROOT_DIR, options);
  if (options.json) {
    console.log(JSON.stringify(report, null, 2));
  } else {
    printHumanReport(report);
  }
}
